spring:
  application:
    name: myecom-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
    driver-class-name: org.postgresql.Driver
server:
  port: 8081