DROP TABLE IF EXISTS users.users;
DROP TABLE IF EXISTS users.credentials;

CREATE TABLE users.users
(
    user_id    UUID         NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    image_url  TEXT,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(20),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE users.credentials
(
    credential_id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITHOUT TIME ZONE,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE,
    username                   VARCHAR(255)                             NOT NULL,
    password                   TEXT                                     NOT NULL,
    role                       VARCHAR(255),
    is_enabled                 BOOLEAN DEFAULT TRUE,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    user_id                    UUID,
    CONSTRAINT pk_credentials PRIMARY KEY (credential_id)
);

ALTER TABLE users.credentials
    ADD CONSTRAINT uc_credentials_user UNIQUE (user_id);

ALTER TABLE users.credentials
    ADD CONSTRAINT uc_credentials_username UNIQUE (username);

ALTER TABLE users.credentials
    ADD CONSTRAINT FK_CREDENTIALS_ON_USER FOREIGN KEY (user_id) REFERENCES users.users (user_id);